/*
  func Helper gen actionType
*/
export const asyncTypes = action => ({
  ORIGIN: action,
  HANDLER: `${action}_HANDLER`,
  PENDING: `${action}_PENDING`,
  START: `${action}_START`,
  MORE: `${action}_MORE`,
  SUCCESS: `${action}_SUCCESS`,
  FAILURE: `${action}_FAILURE`,
  ERROR: `${action}_ERROR`,
  CLEAR: `${action}_CLEAR`,
  STORE: `${action}_STORE`,
  END: `${action}_END`,
  REMOVE: `${action}_REMOVE`,
  SWITCH: `${action}_SWITCH`,
  CHANGE: `${action}_CHANGE`,
});
/*
  CONNECTIVITY
  - receive, sound notification
*/
export const CONNECTIVITY = {
  APP_CONNECTIVITY_CHANGE: 'CONNECTIVITY/APP_CONNECTIVITY_CHANGE',
};

export const ERROR = {
  SHOW: asyncTypes('ERROR/SHOW'),
  HIDE: asyncTypes('ERROR/HIDE'),
};

export const AUTH = {
  LOG_OUT: asyncTypes('AUTH/LOG_OUT'),
  GET_OTP: asyncTypes('AUTH/GET_OTP'),
  CONFIRM_OTP: asyncTypes('AUTH/CONFIRM_OTP'),
  CLEAR_ERROR: asyncTypes('AUTH/CLEAR_ERROR'),
  INPUT_ACTION: asyncTypes('AUTH/INPUT_ACTION'),
  CHECK_EXISTED: asyncTypes('AUTH/CHECK_EXISTED'),
  REFRESH_TOKEN: asyncTypes('AUTH/REFRESH_TOKEN'),
  VERIFY_REFERRAL: asyncTypes('AUTH/VERIFY_REFERRAL'),
  MEMBER_VIEW_POINT: asyncTypes('AUTH/MEMBER_VIEW_POINT'),
  SETUP_PIN_CODE: asyncTypes('AUTH/SETUP_PIN_CODE'),
  LOGIN_PIN_CODE: asyncTypes('AUTH/LOGIN_PIN_CODE'),
  TURNON_LOGIN_PIN_CODE: asyncTypes('AUTH/TURNON_LOGIN_PIN_CODE'),
  TURNOFF_LOGIN_PIN_CODE: asyncTypes('AUTH/TURNOFF_LOGIN_PIN_CODE'),
  TOGGLE_BIOMETRIC: asyncTypes('AUTH/TOGGLE_BIOMETRIC'),
  LOGIN_BIOMETRIC: asyncTypes('AUTH/LOGIN_BIOMETRIC'),
  RESET_ERROR: asyncTypes('AUTH/RESET_ERROR'),
  UPDATE_PHONE_NUMBER: asyncTypes('AUTH/UPDATE_PHONE_NUMBER'),
  UPDATE_TOKEN: asyncTypes('AUTH/UPDATE_TOKEN'),
  GET_REFRESH_TOKEN: asyncTypes('AUTH/GET_REFRESH_TOKEN'),
  GET_ACCESS_TOKEN: asyncTypes('AUTH/GET_ACCESS_TOKEN'),
  GET_OTP_IN_APP: asyncTypes('AUTH/GET_OTP_IN_APP'),
  REQUEST_DELETE_ACCOUNT: asyncTypes('AUTH/REQUEST_DELETE_ACCOUNT'),
};

export const HOME = {
  GET_HOME_DATA: asyncTypes('HOME/GET_HOME_DATA'),
  GET_POP_UP: asyncTypes('HOME/GET_POP_UP'),
};

export const NEWS = {
  GET_ARTICLE_DETAIL: asyncTypes('NEWS/GET_ARTICLE_DETAIL'),
  GET_ALL_ARTICLE: asyncTypes('NEWS/GET_ALL_ARTICLE'),
};

export const STORE = {
  GET_ALL_STORE: asyncTypes('STORE/GET_ALL_STORE'),
  GET_STORE_FILTER: asyncTypes('STORE/GET_STORE_FILTER'),
};

export const SURVEY = {
  GET_SURVEY_BY_ID: asyncTypes('SURVEY/GET_SURVEY_BY_ID'),
  SUBMIT_SURVEY_ANSWER: asyncTypes('SURVEY/SUBMIT_SURVEY_ANSWER'),
  CLEAR_SUBMIT_ERROR: asyncTypes('SURVEY/CLEAR_SUBMIT_ERROR'),
  CHECK_MEMBER_TAKING_SURVEY: asyncTypes('SURVEY/CHECK_MEMBER_TAKING_SURVEY'),
  SET_SURVEY_FROM_NOTIFICATION: 'SURVEY/SET_SURVEY_FROM_NOTIFICATION',
};

export const FAQ = {
  GET_ALL_FAQ: asyncTypes('FAQ/GET_ALL_FAQ'),
  GET_ALL_FAQ_FILTER: asyncTypes('FAQ/GET_ALL_FAQ_FILTER'),
  GET_POLICY: asyncTypes('FAQ/GET_POLICY'),
  SUBMIT_SUPPORT_REQUEST: asyncTypes('FAQ/SUBMIT_SUPPORT_REQUEST'),
};

export const EVENT = {
  GET_ALL_EVENT: asyncTypes('EVENT/GET_ALL_EVENT'),
  SUBMIT_EVENT_RESPONSE: asyncTypes('EVENT/SUBMIT_EVENT_RESPONSE'),
  STORE_LIST_CALENDAR: asyncTypes('EVENT/STORE_LIST_CALENDAR'),
  CLEAR_EVENT_CALENDAR: asyncTypes('EVENT/CLEAR_EVENT_CALENDAR'),
  REMOVE_EVENT_CALENDAR: asyncTypes('EVENT/REMOVE_EVENT_CALENDAR'),
  GET_ALL_MY_EVENT: asyncTypes('EVENT/GET_ALL_MY_EVENT'),
  GET_MY_EVENT_FILTER: asyncTypes('EVENT/GET_MY_EVENT_FILTER'),
  GET_EVENT_DETAIL: asyncTypes('EVENT/GET_EVENT_DETAIL'),
};

export const VOUCHER = {
  GET_LIST_VOUCHERS_BY_SORTING: asyncTypes(
    'VOUCHER/GET_LIST_VOUCHERS_BY_SORTING',
  ),
  GET_LIST_VOUCHERS_GROUP: asyncTypes('VOUCHER/GET_LIST_VOUCHERS_GROUP'),
  REDEEM_VOUCHER: asyncTypes('VOUCHER/REDEEM_VOUCHER'),
  GET_LIST_REDEEMED_VOUCHER: asyncTypes('VOUCHER/GET_LIST_REDEEMED_VOUCHER'),
  GET_LIST_INACTIVE_VOUCHER: asyncTypes('VOUCHER/GET_LIST_INACTIVE_VOUCHER'),
  USE_VOUCHER: asyncTypes('VOUCHER/USE_VOUCHER'),
  GET_DATA_BY_SUGGEST: asyncTypes('VOUCHER/GET_DATA_BY_SUGGEST'),
  SEARCH_VOUCHERS: asyncTypes('VOUCHER/SEARCH_VOUCHERS'),
  GET_VOUCHER_DETAIL: asyncTypes('VOUCHER/GET_VOUCHER_DETAIL'),
  GET_VOUCHER_TYPE: asyncTypes('VOUCHER/GET_VOUCHER_TYPE'),
  RESET_ERROR: asyncTypes('VOUCHER/RESET_ERROR'),
  GET_REDEEMED_VOUCHER_DETAIL: asyncTypes(
    'VOUCHER/GET_REDEEMED_VOUCHER_DETAIL',
  ),
  UPDATE_WISHLIST: asyncTypes('VOUCHER/UPDATE_WISHLIST'),
  GET_WISHLIST_BY_MEMBER: asyncTypes('VOUCHER/GET_WISHLIST_BY_MEMBER'),
};

export const PROFILE = {
  GET_PROFILE: asyncTypes('PROFILE/GET_PROFILE'),
  UPDATE_PROFILE: asyncTypes('PROFILE/UPDATE_PROFILE'),
  GET_OTP_PROFILE: asyncTypes('PROFILE/GET_OTP_PROFILE'),
  EXISTED_PROFILE: asyncTypes('PROFILE/EXISTED_PROFILE'),
  CONFIRM_CODE_PROFILE: asyncTypes('PROFILE/CONFIRM_CODE_PROFILE'),
  GET_OTP_EMAIL: asyncTypes('PROFILE/GET_OTP_EMAIL'),
  VERIFY_OTP_EMAIL: asyncTypes('PROFILE/VERIFY_OTP_EMAIL'),
  CLEAR_ERROR: asyncTypes('PROFILE/CLEAR_ERROR'),
  CLEAR_PROFILE: asyncTypes('PROFILE/CLEAR_PROFILE'),
};

export const CHALLENGE = {
  GET_LIST_BY_MEMBER_CODE: asyncTypes('CHALLENGE/GET_LIST_BY_MEMBER_CODE'),
  JOIN_CHALLENGE: asyncTypes('CHALLENGE/JOIN_CHALLENGE'),
  GET_LIST_CHALLENGE_HOT: asyncTypes('CHALLENGE/GET_LIST_CHALLENGE_HOT'),
  CLEAR_CHALLENGES_LIST: asyncTypes('CHALLENGE/CLEAR_CHALLENGES_LIST'),
  GET_MY_CHALLENGE: asyncTypes('CHALLENGE/GET_MY_CHALLENGE'),
  GET_CHALLENGE_DETAIL: asyncTypes('CHALLENGE/GET_CHALLENGE_DETAIL'),
  RESET_ERROR: asyncTypes('CHALLENGE/RESET_ERROR'),
};

export const RANK = {
  GET_ALL_RANKS: asyncTypes('RANK/GET_ALL_RANKS'),
};

export const TRANSACTIONS = {
  GET_CLAIM_HISTORY: asyncTypes('TRANSACTIONS/GET_CLAIM_HISTORY'),
  GET_REDEEM_HISTORY: asyncTypes('TRANSACTIONS/GET_REDEEM_HISTORY'),
  GET_ORDER_HISTORY: asyncTypes('TRANSACTIONS/GET_ORDER_HISTORY'),
  CLEAR_TRANSACTIONS: asyncTypes('TRANSACTIONS/CLEAR_TRANSACTIONS'),
};

export const NOTIFICATION = {
  UPDATE_NOTIFICATION_SETTING: asyncTypes(
    'NOTIFICATION/UPDATE_NOTIFICATION_SETTING',
  ),
  GET_ALL_NOTIFICATION: asyncTypes('NOTIFICATION/GET_ALL_NOTIFICATION'),
  GET_GENERAL_NOTIFICATION: asyncTypes('NOTIFICATION/GET_GENERAL_NOTIFICATION'),
  GET_PRIVATE_NOTIFICATION: asyncTypes('NOTIFICATION/GET_PRIVATE_NOTIFICATION'),
  DELETE_NOTIFICATION: asyncTypes('NOTIFICATION/DELETE_NOTIFICATION'),
  READ_NOTIFICATION: asyncTypes('NOTIFICATION/READ_NOTIFICATION'),
  GET_NOTIFICATION_SETTING: asyncTypes('NOTIFICATION/GET_NOTIFICATION_SETTING'),
  REMOVE_ALL_NOTIFICATION: asyncTypes('NOTIFICATION/REMOVE_ALL_NOTIFICATION'),
};

export const SYSTEM = {
  SHOW_ERROR: asyncTypes('SYSTEM/SHOW_ERROR'),
  CLEAR_ERROR: asyncTypes('SYSTEM/CLEAR_ERROR'),
  UPDATE_CONNECTION_STATUS: asyncTypes('SYSTEM/UPDATE_CONNECTION_STATUS'),
  SET_NEED_UPDATE_VERSION: 'SYSTEM/SET_NEED_UPDATE_VERSION',
};

export const SECURITY = {
  GET_OTP_FORGET: asyncTypes('SECURITY/GET_OTP_FORGET'),
  CONFIRM_OTP_FORGET: asyncTypes('SECURITY/CONFIRM_OTP_FORGET'),
  CLEAR_ERROR: asyncTypes('SECURITY/CLEAR_ERROR'),
  CONFIRM_CURRENT_PIN_CODE: asyncTypes('SECURITY/CONFIRM_CURRENT_PIN_CODE'),
};
